[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mai"
version = "0.1.0" 
description = "dynamic ai library from scratch"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Spencer Toupin" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "numpy>=1.24",
  "pandas>=2.0",
  "scikit-learn>=1.3",
  "kagglehub[pandas-datasets]>=0.3",
  "matplotlib>=3.9,<3.10"
]

[tool.setuptools.packages.find]
where = ["src"]